/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge;

public class ArrayShift{
    public int[] insertShiftArray(int[] array, int input){
        int [] shiftedArray = new int [array.length +1];
        float location = (float) array.length/2;
        location = Math.round(location);
        for(int i = 0; i < shiftedArray.length;i++) {
            if (i < location) {
                shiftedArray[i] = array[i];
            }
            else if(i == location){
                shiftedArray[i] = input;

            }
            else{
                shiftedArray[i] = array[i-1];
            }
        }

        return shiftedArray;
    }
}
